name       : haskell-mono-traversable
version    : 1.0.15.1
release    : 3
source     :
    - https://hackage.haskell.org/package/mono-traversable-1.0.15.1/mono-traversable-1.0.15.1.tar.gz : c2df5b79ed2f88f2ee313e57c1d591d4463788e20d39e439297eec5ba5835ddf
license    : MIT
component  : programming.haskell
summary    : Monomorphic variants of the Functor, Foldable, and Traversable typeclasses.
description: |
    Monomorphic variants of the Functor, Foldable, and Traversable typeclasses.
builddeps  :
    - haskell-cabal-install
    - haskell-split-devel
    - haskell-unordered-containers-devel
    - haskell-vector-algorithms-devel
rundeps    :
    - devel:
        - haskell-split-devel
        - haskell-unordered-containers-devel
        - haskell-vector-algorithms-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
