name       : haskell-mono-traversable
version    : 1.0.8.1
release    : 2
source     :
    - https://hackage.haskell.org/package/mono-traversable-1.0.8.1/mono-traversable-1.0.8.1.tar.gz : 991290797bd77ce2f2e23dd5dea32fb159c6cb9310615f64a0703ea4c6373935
license    : MIT
component  : programming.haskell
summary    : Monomorphic variants of the Functor, Foldable, and Traversable typeclasses.
description: |
    Monomorphic variants of the Functor, Foldable, and Traversable typeclasses.
builddeps  :
    - haskell-cabal-install
    - haskell-split
    - haskell-unordered-containers
    - haskell-vector-algorithms
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
