name       : haskell-mono-traversable
version    : 1.0.2
release    : 1
source     :
    - http://hackage.haskell.org/package/mono-traversable-1.0.2/mono-traversable-1.0.2.tar.gz : aa110a1f08b726f2e0d17858e09bd76e13d60ccf2bf5366c92c15999da0b3633
license    : MIT
component  : programming.haskell
summary    : Monomorphic variants of the Functor, Foldable, and Traversable typeclasses.
description: |
    Monomorphic variants of the Functor, Foldable, and Traversable typeclasses.
builddeps  :
    - haskell-cabal-install
    - haskell-split
    - haskell-unordered-containers
    - haskell-vector-algorithms
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
